/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as PlanRouteImport } from './routes/plan'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SyllabusIndexRouteImport } from './routes/syllabus.index'
import { Route as SyllabusSubjectIdRouteImport } from './routes/syllabus.$subjectId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const PlanRoute = PlanRouteImport.update({
  id: '/plan',
  path: '/plan',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SyllabusIndexRoute = SyllabusIndexRouteImport.update({
  id: '/syllabus/',
  path: '/syllabus/',
  getParentRoute: () => rootRouteImport,
} as any)
const SyllabusSubjectIdRoute = SyllabusSubjectIdRouteImport.update({
  id: '/syllabus/$subjectId',
  path: '/syllabus/$subjectId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/onboarding': typeof OnboardingRoute
  '/plan': typeof PlanRoute
  '/settings': typeof SettingsRoute
  '/syllabus/$subjectId': typeof SyllabusSubjectIdRoute
  '/syllabus/': typeof SyllabusIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/onboarding': typeof OnboardingRoute
  '/plan': typeof PlanRoute
  '/settings': typeof SettingsRoute
  '/syllabus/$subjectId': typeof SyllabusSubjectIdRoute
  '/syllabus': typeof SyllabusIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/onboarding': typeof OnboardingRoute
  '/plan': typeof PlanRoute
  '/settings': typeof SettingsRoute
  '/syllabus/$subjectId': typeof SyllabusSubjectIdRoute
  '/syllabus/': typeof SyllabusIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/onboarding'
    | '/plan'
    | '/settings'
    | '/syllabus/$subjectId'
    | '/syllabus/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/onboarding'
    | '/plan'
    | '/settings'
    | '/syllabus/$subjectId'
    | '/syllabus'
  id:
    | '__root__'
    | '/'
    | '/onboarding'
    | '/plan'
    | '/settings'
    | '/syllabus/$subjectId'
    | '/syllabus/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  OnboardingRoute: typeof OnboardingRoute
  PlanRoute: typeof PlanRoute
  SettingsRoute: typeof SettingsRoute
  SyllabusSubjectIdRoute: typeof SyllabusSubjectIdRoute
  SyllabusIndexRoute: typeof SyllabusIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plan': {
      id: '/plan'
      path: '/plan'
      fullPath: '/plan'
      preLoaderRoute: typeof PlanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/syllabus/': {
      id: '/syllabus/'
      path: '/syllabus'
      fullPath: '/syllabus/'
      preLoaderRoute: typeof SyllabusIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/syllabus/$subjectId': {
      id: '/syllabus/$subjectId'
      path: '/syllabus/$subjectId'
      fullPath: '/syllabus/$subjectId'
      preLoaderRoute: typeof SyllabusSubjectIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  OnboardingRoute: OnboardingRoute,
  PlanRoute: PlanRoute,
  SettingsRoute: SettingsRoute,
  SyllabusSubjectIdRoute: SyllabusSubjectIdRoute,
  SyllabusIndexRoute: SyllabusIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
